### PR TITLE
Move sketch to appropriately named subfolder

### PR DESCRIPTION
**Pull request by per1234**
The Arduino IDE requires that a sketch be located in a folder of the same name. Although the name of the repository does match the sketch name, when GitHub's popular **Clone or download > Download ZIP** feature is used to download a repository the branch/release/commit name is appended to the folder name, causing a mismatch.

When opening a file that does not meet this sketch/folder name matching requirement the Arduino IDE presents a dialog:
```
The file "MarantzVolumeMonitor.ino" needs to be inside a sketch folder named "MarantzVolumeMonitor".
Create this folder, move the file, and continue?
```
After clicking "OK" the Arduino IDE currently moves only the file MarantzVolumeMonitor.ino to the new folder, leaving behind the other source files. This causes compilation of the sketch to fail:
```
MarantzVolumeMonitor-master\MarantzVolumeMonitor\MarantzVolumeMonitor.ino:1:27: fatal error: MarantzClient.h: No such file or directory

 #include "MarantzClient.h"
```

### CODE REVIEW

**Comment by tillig** [comment]
Ah, I see what you're looking for. I actually develop using Visual Studio and the [Visual Micro add-in](http://www.visualmicro.com/) rather than the classic Arduino IDE. I can move things, but I need to update the .sln, the .vcxproj, and any other artifacts that Visual Micro requires to point to libraries.

Let me switch this over to be an issue and I can take care of it. It might be a little bit since I'm in the middle of troubleshooting an issue I've found with the latest firmware update to my receiver not reliably serving data; I need to finish that up before I can rearrange the files.

Thanks!

**Comment by per1234** [comment]
I checked MarantzVolumeMonitor.sln, MarantzVolumeMonitor.vcxproj, and MarantzVolumeMonitor.vcxproj.filters and it looks like only MarantzVolumeMonitor.vcxproj needs to be changed. I believe I have updated all the paths:
https://github.com/per1234/MarantzVolumeMonitor/commit/d4451b9bcb162a76391b6ff3a07f2e247be37c0f

**Comment by tillig** [comment]
The thing is, I don't want the solution down in that folder. Don't worry, I'll take care of it. Like I said, I appreciate the work here, I just need to make sure it'll work for everyone.

**Comment by tillig** [comment]
Sorry for the delay, this has been done. Thanks for your patience!

**Pull request closed without merging**
